name: Deploy Telegram KDoc Pages
on:
  push:
    branches:
      - kdoc-deploy/component-telegram

jobs:
  deploy-telegram-kdoc-pages:
    name: deploy-telegram-kdoc-pages
    runs-on: ubuntu-latest
    steps:
      # 检出仓库代码
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/github-pages-action
      - name: Deploy component/telegram to doc repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PUSH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: components/telegram
          destination_dir: components/telegram
