name: Deploy Main V5 KDoc Pages
on:
  push:
    branches: 'kdoc-deploy/main-v5'

# 添加 concurrency 配置
concurrency:
  group: deploy-to-gh-pages   # 发布目标为 gh-pages 分支的任务使用同一个 group name
  cancel-in-progress: false   # 如果有新的运行，是否取消进行中的运行

jobs:
  deploy-main-v5-kdoc-pages:
    name: deploy-main-v5-kdoc-pages
    runs-on: ubuntu-latest
    steps:
      # 检出仓库代码
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/github-pages-action
      - name: Deploy main-v5 to doc repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PUSH_TOKEN }}
          publish_branch: gh-pages
          # 前缀为 snapshots
          publish_dir: main-v5
          destination_dir: main-v5
