name: Deploy Index Page
on:
  push:
    branches: [doc-index]

jobs:
  deploy-doc:
    name: deploy-index-page
    runs-on: ubuntu-latest
    steps:
      # 检出仓库代码
      - uses: actions/checkout@v3

        # setup nodejs
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - uses: actions/checkout@v3
        with:
          ref: 'kdoc-deploy/main'
          path: 'public'

      - uses: actions/checkout@v3
        with:
          ref: 'kdoc-deploy/component-mirai'
          path: 'public'

      - uses: actions/checkout@v3
        with:
          ref: 'kdoc-deploy/component-kook'
          path: 'public'

      - uses: actions/checkout@v3
        with:
          ref: 'kdoc-deploy/component-tencent-guild'
          path: 'public'


      - run: npm ci
      - run: npm run build

      # https://github.com/marketplace/actions/github-pages-action
      - name: Push to doc repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PUSH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          keep_files: true
