name: Deploy Index Page
on:
  push:
    branches: 'doc-index'

jobs:
  deploy-doc:
    name: deploy-index-page
    runs-on: ubuntu-latest
    steps:
      # 检出仓库代码
      - uses: actions/checkout@v3

        # setup nodejs
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

        # releases

      - uses: actions/checkout@v3
        with:
          ref: 'kdoc-deploy/main'
          path: 'public/kdoc/main'

      - run: |
          cp -r kdoc/main/* ./
          rm -rf kdoc/main
        working-directory: ./public

      - uses: actions/checkout@v3
        with:
          ref: 'kdoc-deploy/component-mirai'
          path: 'public/kdoc/cp-mirai'

      - run: |
          cp -r kdoc/cp-mirai/* ./
          rm -rf kdoc/cp-mirai
        working-directory: ./public

      - uses: actions/checkout@v3
        with:
          ref: 'kdoc-deploy/component-kook'
          path: 'public/kdoc/cp-kook'

      - run: |
          cp -r kdoc/cp-kook/* ./
          rm -rf kdoc/cp-kook
        working-directory: ./public

      - uses: actions/checkout@v3
        with:
          ref: 'kdoc-deploy/component-qq-guild'
          path: 'public/kdoc/cp-tcg'

      - run: |
          cp -r kdoc/cp-tcg/* ./
          rm -rf kdoc/cp-tcg
        working-directory: ./public

      # snapshots

#       - uses: actions/checkout@v3
#         with:
#           ref: 'kdoc-deploy/main'
#           path: 'public/kdoc/snapshot/main'

#       - run: |
#           cp -r kdoc/main/* ./
#           rm -rf kdoc/main
#         working-directory: ./public

#       - uses: actions/checkout@v3
#         with:
#           ref: 'kdoc-deploy/component-mirai'
#           path: 'public/kdoc/cp-mirai'

#       - run: |
#           cp -r kdoc/cp-mirai/* ./
#           rm -rf kdoc/cp-mirai
#         working-directory: ./public

#       - uses: actions/checkout@v3
#         with:
#           ref: 'kdoc-deploy/component-kook'
#           path: 'public/kdoc/cp-kook'

#       - run: |
#           cp -r kdoc/cp-kook/* ./
#           rm -rf kdoc/cp-kook
#         working-directory: ./public

      - uses: actions/checkout@v3
        with:
          ref: 'kdoc-deploy/snapshot/component-qq-guild'
          path: 'public/kdoc/snapshot/cp-qg'

      - run: |
          cp -r kdoc/snapshot/cp-qg/* ./
          rm -rf kdoc/snapshot/cp-qg
        working-directory: ./public

      - run: |
          npm ci
          npm run build

      # https://github.com/marketplace/actions/github-pages-action
      - name: Push to doc repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PUSH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          cname: docs.simbot.forte.love
